version: '3'

services:
  ceph-admin:
    image: ceph-admin-node
    container_name: ceph-admin
    hostname: ceph-admin
#    privileged: true
#    devices:
#      - "/dev/sdc:/dev/sdc"
    tty: true

  ceph-mon-1:
    image: ceph-infra-node
    container_name: ceph-mon-1
    hostname: ceph-mon-1
    privileged: true
    expose:
      - "6789"
#    volumes:
#      - /var/lib/ceph-mon-1:/var/lib/ceph

  ceph-mon-2:
    image: ceph-infra-node
    container_name: ceph-mon-2
    hostname: ceph-mon-2
    privileged: true
    expose:
      - "6789"
#    volumes:
#      - /var/lib/ceph-mon-2:/var/lib/ceph

  ceph-mon-3:
    image: ceph-infra-node
    container_name: ceph-mon-3
    hostname: ceph-mon-3
    privileged: true
    expose:
      - "6789"
#    volumes:
#      - /var/lib/ceph-mon-3:/var/lib/ceph

  ceph-mgr-1:
    image: ceph-infra-node
    container_name: ceph-mgr-1
    hostname: ceph-mgr-1
    privileged: true
    expose:
      - "6800-7300"

  ceph-osd-1:
    image: ceph-infra-node
    container_name: ceph-osd-1
    hostname: ceph-osd-1
    privileged: true
    expose:
      - "6800-6810"

  ceph-osd-2:
    image: ceph-infra-node
    container_name: ceph-osd-2
    hostname: ceph-osd-2
    privileged: true
    expose:
      - "6800-6810"

  ceph-osd-3:
    image: ceph-infra-node
    container_name: ceph-osd-3
    hostname: ceph-osd-3
    privileged: true
    expose:
      - "6800-6810"
