version: '3'

services:
  ceph-admin:
    image: ceph-admin-node
    container_name: ceph-admin
    hostname: ceph-admin
    tty: true

  ceph-mon-0:
    image: ceph-infra-node
    container_name: ceph-mon-0
    hostname: ceph-mon-0
    privileged: true
    expose:
      - "6789"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - /var/lib/ceph-mon-0:/var/lib/ceph

  ceph-mon-1:
    image: ceph-infra-node
    container_name: ceph-mon-1
    hostname: ceph-mon-1
    privileged: true
    expose:
      - "6789"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - /var/lib/ceph-mon-0:/var/lib/ceph

  ceph-mon-2:
    image: ceph-infra-node
    container_name: ceph-mon-2
    hostname: ceph-mon-2
    privileged: true
    expose:
      - "6789"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - /var/lib/ceph-mon-2:/var/lib/ceph

  ceph-mgr-0:
    image: ceph-infra-node
    container_name: ceph-mgr-0
    hostname: ceph-mgr-0
    privileged: true
    expose:
      - "6800-7300"
    ports:
      - "8080:8080"
      - "8443:8443"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ceph-osd-0:
    image: ceph-infra-node
    container_name: ceph-osd-0
    hostname: ceph-osd-0
    privileged: true
    expose:
      - "6800-6810"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ceph-osd-1:
    image: ceph-infra-node
    container_name: ceph-osd-1
    hostname: ceph-osd-1
    privileged: true
    expose:
      - "6800-6810"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ceph-osd-2:
    image: ceph-infra-node
    container_name: ceph-osd-2
    hostname: ceph-osd-2
    privileged: true
    expose:
      - "6800-6810"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ceph-rgw-0:
    image: ceph-infra-node
    container_name: ceph-rgw-0
    hostname: ceph-rgw-0
    privileged: true
    ports:
      - "80:7480"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
