version: '3'

services:
  ceph-admin:
    image: ceph-admin-node
    container_name: ceph-admin
    hostname: ceph-admin
#    privileged: true
#    devices:
#      - "/dev/sdc:/dev/sdc"
    tty: true

  ceph-mon-1:
    image: ceph-infra-node
    container_name: ceph-mon-1
    hostname: ceph-mon-1
    privileged: true
    expose:
      - "6789"
#    volumes:
#      - /var/lib/ceph-mon-1:/var/lib/ceph

  ceph-mon-2:
    image: ceph-infra-node
    container_name: ceph-mon-2
    hostname: ceph-mon-2
    privileged: true
    expose:
      - "6789"
#    volumes:
#      - /var/lib/ceph-mon-2:/var/lib/ceph

  ceph-mon-3:
    image: ceph-infra-node
    container_name: ceph-mon-3
    hostname: ceph-mon-3
    privileged: true
    expose:
      - "6789"
#    volumes:
#      - /var/lib/ceph-mon-3:/var/lib/ceph

  ceph-mgr-1:
    image: ceph-infra-node
    container_name: ceph-mgr-1
    hostname: ceph-mgr-1
    privileged: true
    expose:
      - "6800-7300"

  ceph-ods-1:
    image: ceph-infra-node
    container_name: ceph-ods-1
    hostname: ceph-ods-1
    privileged: true
    expose:
      - "6800-6810"

  ceph-ods-2:
    image: ceph-infra-node
    container_name: ceph-ods-2
    hostname: ceph-ods-2
    privileged: true
    expose:
      - "6800-6810"

  ceph-ods-3:
    image: ceph-infra-node
    container_name: ceph-ods-3
    hostname: ceph-ods-3
    privileged: true
    expose:
      - "6800-6810"
