version: '3'

services:
  ceph-admin:
    image: ceph-admin-node
    container_name: ceph-admin
    hostname: ceph-admin
    tty: true

  ceph-mon-1:
    image: ceph-infra-node
    container_name: ceph-mon-1
    hostname: ceph-mon-1
    privileged: true
    expose:
      - "6789"

  ceph-mon-2:
    image: ceph-infra-node
    container_name: ceph-mon-2
    hostname: ceph-mon-2
    privileged: true
    expose:
      - "6789"

  ceph-mon-3:
    image: ceph-infra-node
    container_name: ceph-mon-3
    hostname: ceph-mon-3
    privileged: true
    expose:
      - "6789"

  ceph-mgr-1:
    image: ceph-infra-node
    container_name: ceph-mgr-1
    hostname: ceph-mgr-1
    privileged: true
    expose:
      - "6800-7300"
